# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('energy-module-nbiot', ['core','energy'])
    module.source = [
        'model/energy-module-nbiot.cc',
        'helper/energy-module-nbiot-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('energy-module-nbiot')
    module_test.source = [
        'test/energy-module-nbiot-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'energy-module-nbiot'
    headers.source = [
        'model/energy-module-nbiot.h',
        'helper/energy-module-nbiot-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

